project:
  type: book
  output-dir: docs

book:
  title: "Orientaciones labor tutorial FACSO"
  author: "Equipo Centro IDEA"
  date: "24-04-2025"
  reader-mode: true
  page-footer:
      left: | 
        Centro para la Innovación de la Enseñanza y el Aprendizaje (Centro IDEA)

      right: |
        Este libro se construyó con <a href="https://quarto.org/">Quarto</a>.
  page-navigation: true
  cover-image: logo.jpg
  favicon: logo.jpg
#  repo-url: https://github.com/educacion-meritocracia/reporte-colegios
  repo-branch: main
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd 
    - acompanamiento.qmd
    - administrativo.qmd
    - references.qmd
  search:
    location: sidebar
    type: textbox
  sidebar:
    search: true
    style: docked
    pinned: false


format:
  html:
   # include-before-body: banner.qmd
    toc: true
    toc-location: right
    toc-depth: 6
    toc-expand: 6
    toc-title: Contenidos
    number-sections: false
  #  number-depth: 6
    theme:
     # - pp.scss
     - united
    code-link: true
  pdf:
    documentclass: scrreprt
    title-block-banner: true
    
editor: visual
lang: es
#bibliography: Educacion-meritocracia.bib
