---
title: "Acompañamiento"
format:
  html:
    theme: default
    css: styles.css
---

El eje principal de nuestra labor es el acompañamiento integral a estudiantes. Esto implica planificar sesiones enfocadas en las necesidades particulares de este. 

# Acompamiento en años anteriores

El acompañamient impartido tradc¿cionalmente se componet por dos iniciativas: tutorías prsoanlziadas y articulación con ramos mediante talleres

::: {.columns}
::: {.column width="45%"}
## Tutorías personalizadas

::: {.columns}
::: {.column width="30%"}
 Individuales
:::

::: {.column width="15%"}
:::

::: {.column width="50%"}
 Grupales / Grupo de estudio
:::

:::

:::

::: {.column width="5%"}
:::

::: {.column width="45%"}
## Articulación con ramos: **Talleres**

-   masivos
:::

:::

# Acompañamiento desde este semestre

Desde este semestre, si bien se mantiene la logica tradicioal de acompañmiento

::: {.columns}
::: {.column width="45%"}
## Tutorías personalizadas
:::

::: {.column width="5%"}
:::


::: {.column width="45%"}
## Articulación con ramos: **Grupos de estudio** y talleres

-   nuevo enfoque de sistematización de asistencias
:::

:::

# Contexto de movilización de la Facultad: ¿cómo realizamos el acompañamiento?

-   enfatizamos rol de acompañamiento

-   no nos oponemos a la movilización

-   nos desenmarcamos de lo académico

-   grupos de estudio enfocados en el acompañimeto integral del aprendizaje en tiempos de incertidumbre académica

-   gestión adminsitrativa delos equipos para coodridnar so grupso de estudio, detectar necesidades de su carrera y difundir las iniciativas

    -   para ello, deben crear material enfocado en ese objetivo

::: callout-important
-   uso de formulrio de asistencia en reemplazo momentaneao de la lanilla fisica
:::
