---
title: "Tareas Administrativas"
---

Dentro de la labor tutorial, es importante hacer un repote adecuado de su gestión como tutores. Para ello,

::: {.columns}
::: {.column width="40%"}

# Documentos

> documento de trabajo


> planilla de segumiento

>   planill fisica (y su digitalziación)

>   solicitud de sala

:::

::: {.column width="5%"}
:::


::: {.column width="55%"}
# Carpetas

::: {.columns}
::: {.column width="55%"}
Carpetas compartidas **con el equipo de coordinacion**

> carpeta de actas
    
> carpeta de planificaciones

>carpeta de asistencias digitalizdas
    
:::

::: {.column width="5%"}
:::

::: {.column width="40%"}
**Drive del equipo**

> Estructura de carpetas:
>
> ```plaintext
> año/
> └── semestre/
>     └── tutoría-ramo-tutor-a/
> ```
            
:::

:::

:::

:::

::: {.columns}
::: {.column width="95%"}
# Formularios

::: {.columns}
::: {.column width="40%"}
Formularios gestionados **desde coordiancion**

> formulario de inscripcion a talleres

> formulario de solicitud de tutorias personalizadas

> formulario de asistencia tutoias remotas

:::

::: {.column width="15%"}
:::

::: {.column width="40%"}
Formulario gestonaods **desde equipos**

> formulario de inscriocon a grupos de estudio

>  formulario de diagnostico de necesidades

:::  

:::

:::

:::